// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrd4uu7YtDEDm7sN-G3SRNBPhSBbdfKZs',
    appId: '1:173951877370:web:4c301db8d5a46a234b8943',
    messagingSenderId: '173951877370',
    projectId: 'vpn-ad-5feca',
    authDomain: 'vpn-ad-5feca.firebaseapp.com',
    storageBucket: 'vpn-ad-5feca.firebasestorage.app',
    measurementId: 'G-T9F7MEW5FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg5697jwZKJSIt-bUBeRsdxlmbaO9woOo',
    appId: '1:173951877370:android:c29af8eeffa61a724b8943',
    messagingSenderId: '173951877370',
    projectId: 'vpn-ad-5feca',
    storageBucket: 'vpn-ad-5feca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeLYhkn-6s8Vpi-BvgOzAsGySTYOA9iYQ',
    appId: '1:173951877370:ios:fbd36accc2e359ff4b8943',
    messagingSenderId: '173951877370',
    projectId: 'vpn-ad-5feca',
    storageBucket: 'vpn-ad-5feca.firebasestorage.app',
    iosBundleId: 'com.example.vpnServe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeLYhkn-6s8Vpi-BvgOzAsGySTYOA9iYQ',
    appId: '1:173951877370:ios:fbd36accc2e359ff4b8943',
    messagingSenderId: '173951877370',
    projectId: 'vpn-ad-5feca',
    storageBucket: 'vpn-ad-5feca.firebasestorage.app',
    iosBundleId: 'com.example.vpnServe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrd4uu7YtDEDm7sN-G3SRNBPhSBbdfKZs',
    appId: '1:173951877370:web:4d74d6d0e6d426774b8943',
    messagingSenderId: '173951877370',
    projectId: 'vpn-ad-5feca',
    authDomain: 'vpn-ad-5feca.firebaseapp.com',
    storageBucket: 'vpn-ad-5feca.firebasestorage.app',
    measurementId: 'G-9NV5D7S6H5',
  );
}
